name: Fetch RSM Spectrum Data

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install DuckDB and dependencies
      run: |
        # Install DuckDB
        wget https://github.com/duckdb/duckdb/releases/download/v0.9.2/duckdb_cli-linux-amd64.zip
        unzip duckdb_cli-linux-amd64.zip
        sudo mv duckdb /usr/local/bin/
        
        # Install jq for JSON processing
        sudo apt-get update
        sudo apt-get install -y jq curl
    
    - name: Setup SEL environment
      run: |
        # Create SEL directory structure
        mkdir -p $HOME/bronze/{landing/json,archive/json,quarantine/json,logs}
        mkdir -p $HOME/.spectrum_efficiency
        
        # Create config file
        cat > $HOME/.spectrum_efficiency/config << EOF
        API_KEY="${{ secrets.RSM_API_KEY }}"
        EOF
        
        # Make scripts executable
        chmod +x scripts/fetch_Data_RSM.sh
        chmod +x scripts/process_data.sh
        chmod +x scripts/github_upload.sh
    
    - name: Fetch RSM data
      env:
        RSM_API_KEY: ${{ secrets.RSM_API_KEY }}
      run: |
        # Copy your existing fetch script to the working directory
        cp scripts/fetch_Data_RSM.sh ./
        
        # Run the RSM data fetch script
        ./fetch_Data_RSM.sh
    
    - name: Process data and generate CSVs
      run: |
        # Process the DuckDB data into CSV files
        ./scripts/process_data.sh
    
    - name: Update build timestamp
      run: |
        echo "$(date)" > last-updated.txt
        
        # Update HTML file with current timestamp
        current_time=$(date '+%Y-%m-%d %H:%M:%S')
        sed -i "s/Last build: <span id=\"buildTime\">.*<\/span>/Last build: <span id=\"buildTime\">${current_time}<\/span>/g" index.html
    
    - name: Commit and push changes
      run: |
        git config --local user.email "spectrum.efficiency.limited@gmail.com"
        git config --local user.name "spectrumefficiencylimited"
        git add .
        git commit -m "📡 RSM Data Update: $(date '+%Y-%m-%d %H:%M:%S')" || exit 0
        git push

  deploy:
    needs: fetch-data
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
